import React from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import type { StoredAutomation } from "../automation/materialization";
import { compileAutomationRuntime } from "../automation/engine";
import { liquidIce } from "../theme/liquidIce";
import { ContentSurface } from "./ContentSurface";

export function MyAutomationsCard({items,onToggle,onDelete}:{items:StoredAutomation[];onToggle:(item:StoredAutomation)=>void;onDelete:(id:string)=>void}) {
  return <ContentSurface style={styles.card}><Text style={styles.eyebrow}>MEINE AUTOMATIONEN</Text>{items.length===0?<Text style={styles.empty}>Noch keine Automation gespeichert.</Text>:items.map((item,index)=>{const runtime=compileAutomationRuntime(item.definition);return <View key={item.id} style={[styles.row,index>0&&styles.border]}><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.enabled?"AKTIV":"INAKTIV"} · {item.definition.trigger.capabilityId.replace("trigger.","")}{runtime.appleBridgePurpose==="TRIGGER_ONLY"?" · CanMyPhone Engine + Apple Trigger":""}{item.lastRunAt?` · zuletzt ${new Date(item.lastRunAt).toLocaleDateString("de-DE")}`:""}</Text></View><Pressable onPress={()=>onToggle(item)} style={styles.action}><Text style={styles.actionText}>{item.enabled?"Aus":"An"}</Text></Pressable><Pressable onPress={()=>onDelete(item.id)} style={styles.delete}><Text style={styles.deleteText}>Löschen</Text></Pressable></View>})}</ContentSurface>;
}
const styles=StyleSheet.create({card:{marginBottom:14,padding:20},eyebrow:{...liquidIce.type.eyebrow,color:liquidIce.color.automation},empty:{marginTop:12,fontSize:13,color:liquidIce.color.textSecondary},row:{paddingVertical:14,flexDirection:"row",alignItems:"center",gap:8},border:{borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:"rgba(79,94,110,0.14)"},copy:{flex:1},name:{fontSize:15,fontWeight:"700",color:liquidIce.color.textPrimary},meta:{marginTop:4,fontSize:11,color:liquidIce.color.textTertiary},action:{paddingHorizontal:10,paddingVertical:8,borderRadius:14,backgroundColor:"rgba(8,123,255,0.10)"},actionText:{fontSize:12,fontWeight:"700",color:liquidIce.color.accent},delete:{paddingVertical:8},deleteText:{fontSize:11,fontWeight:"600",color:"#C44747"}});
